name: update-packages

on:
  schedule:
    - cron: "17 6 * * 1"
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Force hash update via nix build
        env:
          NIXPKGS_ALLOW_UNFREE: "1"
        run: |
          pkg="jopdf"
          file="pkgs/$pkg/package.nix"
          
          # Forzar las A's de mentira para obligar a Nix a darnos el hash nuevo
          sed -i 's#hash = "sha256-[A-Za-z0-9+/=]\{43\}=";#hash = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";#g' "$file"

          build_output=$(nix build ".#$pkg" --accept-flake-config --impure 2>&1 || true)
          real_hash=$(echo "$build_output" | grep -oE "got:[[:space:]]*sha256-[A-Za-z0-9+/=]+" | cut -d: -f2 | xargs)

          if [ -n "$real_hash" ] && [ "$real_hash" != "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=" ]; then
            sed -i "s#sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=#$real_hash#g" "$file"
          else
            echo "Error: No se pudo capturar el hash real."
            exit 1
          fi

      - name: Format with alejandra
        run: nix run nixpkgs#alejandra -- -q .

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          branch: auto/update-jopdf
          delete-branch: true
          title: "chore: actualización automática de hash para JOPDF"
          commit-message: "chore(jopdf): bump automático de hash remoto"
          body: "Actualización automática del hash usando Nix Actions."
          labels: automated, dependencies

      - name: Auto-merge por CLI
        if: steps.cpr.outputs.pull-request-operation == 'created' || steps.cpr.outputs.pull-request-operation == 'updated'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fusionando el PR #${{ steps.cpr.outputs.pull-request-number }} de forma automática..."
          gh pr merge "${{ steps.cpr.outputs.pull-request-number }}" --merge --delete-branch
